const EPISODES = [
  {
    id: 95,
    epLabel: `CS2`,
    guest: `Russ Davis`,
    title: `Shiba Inu Co-Founder Russ Davis on Meme Coins, Vitalik & What's Next`,
    date: `June 04, 2026`,
    desc: `Live from Consensus 2026 in Miami, we're joined by Russ Davis - " In Russ We Trust " - one of the co-founders of Shiba Inu, the meme coin that changed everything. Russ tells the full story: from passing on Doge in 2016 (a decision that would've been worth $15 million), to taking over Shiba's marketing in February 2021 when it was stuck at a $2M market cap, to watching it explode to $40 billion in eight months.`,
    thumb: `assets/E96_ Russ Davis.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/120973939/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-5-3%2F425467403-44100-2-ba9471dc63cc9.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/CS2-Shiba-Inu-Co-Founder-Russ-Davis-on-Meme-Coins--Vitalik--Whats-Next-e3kab5j`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 94,
    epLabel: `CS3`,
    guest: `Jacqueline Cooper`,
    title: `Crypto Law & Lessons Learned: Jacqueline Cooper on Bitcoin Mining Hacks, Legal Education & Digital Estate Planning`,
    date: `June 03, 2026`,
    desc: `Live from Consensus 2026 in Miami, we're joined by Jacqueline Cooper , also known as CryptoMom2 (we already had CryptoMom No. 1 on this show) ,— partner at Cogent Law Group, co-founder of the Blockchain Legal Institute, and a 10-year veteran of the blockchain space.`,
    thumb: `assets/E97_ Jacqueline Cooper.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/120971287/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-5-3%2F425463705-44100-2-9f5204020866b.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/CS3-Crypto-Law--Lessons-Learned-Jacqueline-Cooper-on-Bitcoin-Mining-Hacks--Legal-Education--Digital-Estate-Planning-e3ka8in`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 93,
    epLabel: `E98`,
    guest: `Jonathan Benton`,
    title: `After 25 Years Fighting Crime at the MET, Jonathan Benton is Recovering Your Stolen Crypto`,
    date: `May 25, 2026`,
    desc: `Jonathan Benton spent 25 years at London's Metropolitan Police - running undercover operations straight out of "The Wire," investigating homicide and counterterrorism, and ultimately leading international corruption cases that took down politicians laundering hundreds of millions through London.`,
    thumb: `assets/E98_ Jonathan Benton.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/120530296/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-4-25%2F424873243-44100-2-17ec1ca9bc185.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E98-After-25-Years-Fighting-Crime-at-the-MET--Jonathan-Benton-is-Recovering-Your-Stolen-Crypto-e3jspto`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 92,
    epLabel: `CS4`,
    guest: `Karen Knox`,
    title: `Karen Knox on Converting to Judaism, Living in Israel & Insuring Crypto`,
    date: `May 20, 2026`,
    desc: `Recorded live at Consensus Miami 2026, I sat down with Karen Knox, digital assets insurance specialist at Howden, for one of the most unexpected origin stories I've heard on this show. From Andy Griffith's hometown in North Carolina, to converting to Judaism, raising her daughter in Tel Aviv, and becoming one of the go-to names in crypto insurance — Karen's path is anything but straight.`,
    thumb: `assets/E100_ Karen Knox.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/120192723/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-4-18%2F424423881-44100-2-11a4d9ca2c269.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/CS4-Karen-Knox-on-Converting-to-Judaism--Living-in-Israel--Insuring-Crypto-e3jig8j`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 91,
    epLabel: `E95`,
    guest: `Delphine Forma`,
    title: `Delphine Forma on Crypto Compliance, DeFi Regulation & Why Degens Need to Grow Up`,
    date: `May 19, 2026`,
    desc: `I sat down with Delphine Forma — Head of Policy Europe at Solidus Labs, founder of the largest crypto compliance Telegram group in existence, and one of the most well-traveled compliance professionals in the space. From Sciences Po in France, to finding loopholes in French tax law, to moving to Tokyo for a guy who dumped her three months later — this one is a ride.`,
    thumb: `assets/E95_ Delphine Forma.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/120214463/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-4-19%2F424460192-44100-2-660f026388471.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E95-Delphine-Forma-on-Crypto-Compliance--DeFi-Regulation--Why-Degens-Need-to-Grow-Up-e3jj5fv`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 90,
    epLabel: `CS1`,
    guest: `Ari Redbord`,
    title: `Ari Redbord on Crypto Crime, Compliance & Building TRM Labs`,
    date: `May 18, 2026`,
    desc: `Recorded live at Consensus Miami 2025, I sat down with Ari Redbord — Global Head of Policy at TRM Labs and former federal prosecutor at the DOJ — to talk about following illicit money through the blockchain, the Beacon Network, AI in law, and why human connection matters more than ever in the age of automation. Plus: shoes.`,
    thumb: `assets/E99_ Ari Redbord.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/120190694/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-4-18%2F424421202-44100-2-b66c5d72e5be.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/CS1-Ari-Redbord-on-Crypto-Crime--Compliance--Building-TRM-Labs-e3jie96`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 89,
    epLabel: `E94`,
    guest: `Itai Kanot`,
    title: `Itai Kanot: How BeeHero Is Using AI to Save Bees and Reinvent Agriculture`,
    date: `April 27, 2026`,
    desc: `In this episode, Yitzy sits down with Itai Kanot , CGO and Co-Founder of BeeHero , the company using IoT sensors, AI, and machine learning to monitor beehives and deliver precision pollination at global scale. Itai grew up in southern Israel as the son of the country’s largest beekeeper.`,
    thumb: `assets/E94_ Itai Kanot.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/119040075/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-3-25%2F422862569-44100-2-7eaee63f05b26.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E94-Itai-Kanot-How-BeeHero-Is-Using-AI-to-Save-Bees-and-Reinvent-Agriculture-e3ifakb`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 88,
    epLabel: ``,
    guest: `Avishay Yanai`,
    title: `Building “Compliant Privacy” for Crypto: Avishay Yanai’s Founder Story`,
    date: `April 20, 2026`,
    desc: `After a six-week hiatus spent between reserve duty and bomb shelters, Beyond the Code is back with Avishay Yanai , co-founder and CEO of Soda Labs . In this episode, Yitzy sits down with one of Israel’s top cryptography minds to unpack the founder journey from academia and VMware to building a startup at the frontier of blockchain privacy.`,
    thumb: `assets/E93_ Avishay Yanai.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/118760523/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-3-20%2F422473824-44100-2-a9dd55092320f.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Building-Compliant-Privacy-for-Crypto-Avishay-Yanais-Founder-Story-e3i6pkb`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 87,
    epLabel: `E92`,
    guest: `Scott Thiel`,
    title: `From Lawyer to Founder: Scott Thiel’s Tokinvest Journey`,
    date: `March 16, 2026`,
    desc: `In this episode of Beyond the Code , Yitzy Hammer sits down with Scott Thiel , CEO and founder of Tokinvest , to explore how real-world asset tokenization is moving from hype to reality. Scott shares his path from award-winning lawyer and legal innovator to startup founder building regulated on-chain investment products in Dubai.`,
    thumb: `assets/E92_ Scott Thiel.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/116997314/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-2-16%2F420115272-44100-2-34f59a2cf483f.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E92-From-Lawyer-to-Founder-Scott-Thiels-Tokinvest-Journey-e3ggvo2`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 86,
    epLabel: `E91`,
    guest: `Erin West`,
    title: `Erin West on the Global Scamdemic`,
    date: `March 09, 2026`,
    desc: `Erin West returns to Beyond the Code to unpack the terrifying scale of today’s global scam economy. A former prosecutor and founder of Operation Shamrock , Erin explains how organized criminal networks built massive scam compounds across Southeast Asia, how human trafficking fuels these operations, and why scams like pig butchering, fake investment platforms, and extortion schemes are affecting far more people than m`,
    thumb: `assets/E91_ Erin West.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/116647958/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-2-9%2F419639844-44100-2-313b31361f15c.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E91-Erin-West-on-the-Global-Scamdemic-e3g6aim`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 85,
    epLabel: ``,
    guest: `Crypto Compliance’s Content`,
    title: `Crypto Compliance’s Content King: Stephen Sargeant on Investigations, LinkedIn, and Building Airdropd`,
    date: `February 23, 2026`,
    desc: `Stephen Sargeant ( Airdropd ) breaks down what crypto compliance actually looks like from the inside: five years at Bitfinex handling investigations and law enforcement requests, why the compliance community is tighter (and more welcoming) than people assume, and how a single 20-minute video to Chainalysis turned into producing their podcast, Public Key .`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1771871072004-c5f4dab6b17a7.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/115931043/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-1-23%2F418671218-44100-2-523f6fc66ea83.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Crypto-Compliances-Content-King-Stephen-Sargeant-on-Investigations--LinkedIn--and-Building-Airdropd-e3fgef3`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 84,
    epLabel: `E89`,
    guest: `Yoni Assia`,
    title: `eToro CEO Yoni Assia on 2008 Survival, Ethereum’s Origins, and the AI Trading Future`,
    date: `February 16, 2026`,
    desc: `I sat down with Yoni Assia , co-founder & CEO of eToro , for a wide-ranging conversation that spans Bitcoin’s earliest days , eToro’s journey through the 2008 crisis , and why Yoni thinks AI agents will soon trade more than humans .`,
    thumb: `assets/E89_ Yoni Assia.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/115602930/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-1-16%2F418232307-44100-2-457282da6190e.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E89-eToro-CEO-Yoni-Assia-on-2008-Survival--Ethereums-Origins--and-the-AI-Trading-Future-e3f6e1i`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 83,
    epLabel: `E88`,
    guest: `Daniel Lo`,
    title: `Crypto Lawyer to Market Maker Exec: Daniel Lo on MAS Licensing, Compliance & AI Workflows`,
    date: `February 15, 2026`,
    desc: `Crypto lawyer-turned-operator Daniel Lo shares an “alternative legal career” journey, sharing how he wen from M&A in Calgary to Managing Director, GM and CLO at Acheron Trading in Singapore. He explains what it’s wearing both the legal and management hat, breaks down how a market maker supports token projects (from white-glove designated market making to execution/OTC), and what it takes to get regulated in 2026’s to`,
    thumb: `assets/E88_ Daniel Lo.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/115538307/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-1-15%2F418146857-44100-2-1ca5efabf0ec1.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E88-Crypto-Lawyer-to-Market-Maker-Exec-Daniel-Lo-on-MAS-Licensing--Compliance--AI-Workflows-e3f4eu3`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 82,
    epLabel: `E87`,
    guest: `Philipp Tsagolov`,
    title: `AttentionFi Explained: Betting on Taylor Swift, Trump & Elon (Trendle CEO Philipp Tsagolov)`,
    date: `February 04, 2026`,
    desc: `Prediction markets are booming - but Philipp Tsag o lov , CEO & co-founder of Trendle , believes the next frontier is attention . In this episode, we talk about “AttentionFi”: markets that let you trade whether a person or topic will gain or lose mindshare online, using an attention index built from signals across X/Twitter, YouTube, and Reddit.`,
    thumb: `assets/E87_ Philipp Tsagolov.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/115034198/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-1-4%2F417473892-44100-2-3260bbd0a074f.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E87-AttentionFi-Explained-Betting-on-Taylor-Swift--Trump--Elon-Trendle-CEO-Philipp-Tsagolov-e3el2km`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 81,
    epLabel: `E86`,
    guest: `Ran Neuner`,
    title: `How Ran Neuner Built Crypto Banter: Hate Comments, Bull Markets, and a $130M Lesson`,
    date: `January 13, 2026`,
    desc: `In Episode 86, Yitzy Hammer interviews Ran Neuner (aka “Crypto Man Ran”), co-founder of Crypto Banter , to unpack the real story behind the brand: the childhood hustle that revealed his entrepreneurial wiring, the obsessive “must-win” mindset he calls constructive paranoia, and the hard-earned lessons from building a company to a reported $150M sale—then later watching $130M evaporate in days during the LUNA collapse`,
    thumb: `assets/E86_ Ran Neuner.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/113732623/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-0-9%2F415783143-44100-2-bcb8d9743da9b.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E86-How-Ran-Neuner-Built-Crypto-Banter-Hate-Comments--Bull-Markets--and-a-130M-Lesson-e3ddbif`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 80,
    epLabel: `E85`,
    guest: `CowSwap’s Anna George`,
    title: `CowSwap’s Anna George: Coincidence of Wants, Intent-Based Trading, and the Next Wave of DeFi UX`,
    date: `January 01, 2026`,
    desc: `This episode is with Anna George , co-founder & CEO of CowSwap / Cow Protocol (originally built inside Gnosis, spun out in 2022). What’s wild is Anna spent about a decade in humanitarian/UN work before getting pulled into crypto in 2017 - partly because she wanted impact, and partly because UN bureaucracy will make anyone want to run away and build something.`,
    thumb: `assets/E85_ Anna George.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/113362507/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2026-0-1%2F415314180-44100-2-265f5a128502c.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E85-CowSwaps-Anna-George-Coincidence-of-Wants--Intent-Based-Trading--and-the-Next-Wave-of-DeFi-UX-e3d224b`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 79,
    epLabel: `E84`,
    guest: `Alex Scheer`,
    title: `ZK Identity, Compliance and MiCA: A Conversation with zkMe CEO Alex Scheer`,
    date: `December 08, 2025`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with David Alexander “Alex” Scheer , founder and CEO of zkMe , a zero-knowledge identity network that lets users prove who they are - and meet KYC/AML requirements - without exposing their personal data.`,
    thumb: `assets/E84_ Alex Scheer.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/111952189/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-11-1%2F413504597-44100-2-644eed857418a.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E84-ZK-Identity--Compliance-and-MiCA-A-Conversation-with-zkMe-CEO-Alex-Scheer-e3bn0rt`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 78,
    epLabel: `E83`,
    guest: `Danielle Tichner`,
    title: `Danielle Tichner on Deep Tech, Venture Building & Bitcoin L2s`,
    date: `December 01, 2025`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Danielle Tichner, founder of W Source, a deep-tech venture builder operating at the intersection of infrastructure, crypto, and global commercialization.`,
    thumb: `assets/E83_ Danielle Tichner.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/111930740/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-10-30%2F413477083-44100-2-1db43a1accf61.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E83-Danielle-Tichner-on-Deep-Tech--Venture-Building--Bitcoin-L2s-e3bmbtk`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 77,
    epLabel: `E82`,
    guest: `Paul Brody`,
    title: `Make Ethereum Your Base Layer: EY’s Paul Brody on Leveraging Ethereum for Business`,
    date: `November 11, 2025`,
    desc: `EY’s Global Blockchain Leader Paul Brody joins Yitzy on Beyond the Code to peel back the curtain on how big companies really operate (“chaos on the inside”), why public blockchains beat private networks, and what it takes to ship serious enterprise workflows on Ethereum.`,
    thumb: `assets/E82_ Paul R. Brody.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/111006808/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-10-11%2F412247655-44100-2-ec4bef0ece5ce.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E82-Make-Ethereum-Your-Base-Layer-EYs-Paul-Brody-on-Leveraging-Ethereum-for-Business-e3aq5ko`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 76,
    epLabel: `E81`,
    guest: `Yehuda Lindell`,
    title: `MPC, Enclaves & Defense-in-Depth: Yehuda Lindell on Securing Crypto`,
    date: `October 28, 2025`,
    desc: `In this episode, Yitzy is joined by Yehuda Lindell —founder of Unbound Security (acquired by Coinbase), longtime professor and one of the earliest researchers in secure multiparty computation (MPC) . We trace his journey from Australia to Israel and from theory to industry, then dive into how Coinbase secures customer assets using layered cryptography: MPC, secure enclaves, HSMs, cold elements, and rigorous review pr`,
    thumb: `assets/E81_ Yehuda Lindell.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/110318766/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-9-28%2F410108479-44100-2-47392f0042c3d.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E81-MPC--Enclaves--Defense-in-Depth-Yehuda-Lindell-on-Securing-Crypto-e3a55ne`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 75,
    epLabel: `E80`,
    guest: `Steve Epstein`,
    title: `Steve Epstein on Post-Quantum Cybersecurity, Breaking RSA, and Saving Blockchains`,
    date: `September 29, 2025`,
    desc: `In this episode of Beyond the Code, Yitzy sits down with Steve Epstein — a distinguished systems/cybersecurity & AI engineer with roots at Bell Labs (alongside Peter Shor & Lov Grover), decades at NDS/Cisco/Synamedia, and currently working at Rafael, in Israel’s defense sector.`,
    thumb: `assets/E80_ Steve Epstein.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/108951368/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-8-29%2F408322473-44100-2-9fa41859be766.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E80-Steve-Epstein-on-Post-Quantum-Cybersecurity--Breaking-RSA--and-Saving-Blockchains-e38rec8`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 74,
    epLabel: `E79`,
    guest: `Jake Adelstein`,
    title: `Jake Adelstein: The Devil Takes Bitcoin — Mt. Gox, Silk Road & Japan's [In]justice System`,
    date: `September 08, 2025`,
    desc: `In this episode, investigative journalist Jake Adelstein ( Tokyo Vice ) joins Yitzy to discuss his newly published book, The Devil Takes Bitcoin , a front-row narrative of the Mt. Gox collapse, where ~850k bitcoin went missing, and the cast of characters that shaped crypto’s formative years—from exchange founder Mark Karpelès to law-enforcement sleuths and the corrupt agents who derailed the Silk Road case.`,
    thumb: `assets/E79_ Jake Adelstein.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/108008124/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-8-8%2F407119195-44100-2-6741c2e09feb8.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E79-Jake-Adelstein-The-Devil-Takes-Bitcoin--Mt--Gox--Silk-Road--Japans-Injustice-System-e37ul7s`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 73,
    epLabel: ``,
    guest: `Jake Chervinsky`,
    title: `Jake Chervinsky on Crypto Law, Policy Battles, and Stablecoin Clarity`,
    date: `September 01, 2025`,
    desc: `In this episode, Yitzy sits down with Jake Chervinsky — currently Chief Legal Officer at Variant , and previously Chief Policy Officer at the Blockchain Association - one of the most recognizable voices in crypto law and policy.`,
    thumb: `assets/E79_ Jake Adelstein.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/107593913/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-7-31%2F406596258-44100-2-8fcdf1fa4c9e4.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/78-Jake-Chervinsky-on-Crypto-Law--Policy-Battles--and-Stablecoin-Clarity-e37i0np`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 72,
    epLabel: `E77`,
    guest: `Ido Bar-On`,
    title: `Ido Bar-On on the Future of Defense Tech`,
    date: `August 04, 2025`,
    desc: `In this episode of Beyond the Code , Yitzy is joined in-studio for the very first time by Ido Bar-On — defense-tech investor, former CBO at XTEND, IDF reservist, and ex-VC at LOOL Ventures. From scaling a startup to $40M in sales to deploying capital from a bomb shelter during the Iran attack, Ido shares a candid, deeply informed perspective on the intersection of defense, venture capital, and innovation in times of `,
    thumb: `assets/E77_ Ido Bar-On.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/106408703/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-7-4%2F405074907-44100-2-7a336f2b78454.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E77-Ido-Bar-On-on-the-Future-of-Defense-Tech-e36dr9v`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 71,
    epLabel: `E76`,
    guest: `Samuel Cardillo`,
    title: `Samuel Cardillo, at 29, has one of the coolest life stories I've ever heard!`,
    date: `July 07, 2025`,
    desc: `In this rollercoaster episode of Beyond the Code , Yitzy Hammer sits down with Samuel Cardillo to uncover the jaw-dropping journey of a self-taught prodigy who went from selling computer viruses at age 9 to co-founding RTFKT , the NFT sneaker company acquired by Nike.`,
    thumb: `assets/E76_ Samuel Cardillo.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/105038584/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-6-4%2F403321590-44100-2-04c1910d7efc2.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E76-Samuel-Cardillo--at-29--has-one-of-the-coolest-life-stories-Ive-ever-heard-e35419o`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 70,
    epLabel: `E75`,
    guest: `Gabe Shapiro`,
    title: `Gabe Shapiro on Cyborgs, MetaLex and Building Smarter Crypto Governance`,
    date: `July 01, 2025`,
    desc: `This week on Beyond the Code , Yitzy sits down with one of the most outspoken minds in crypto law: Gabriel Shapiro . Known for his deep legal chops, unfiltered takes, and pioneering work at the intersection of smart contracts and governance, Gabe takes us through his journey—from tech M&A prodigy to crypto lawyer and decentralization maxi.`,
    thumb: `assets/E75_ Gabriel Shapiro.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/104874630/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-6-1%2F403109859-44100-2-d5eeeeb7e3a3c.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E75-Gabe-Shapiro-on-Cyborgs--MetaLex-and-Building-Smarter-Crypto-Governance-e34v166`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 69,
    epLabel: `E74`,
    guest: `Aaron Payas`,
    title: `Aaron Payas: A Gentleman, a Crypto Lawyer and an [ex-] Footballer.`,
    date: `June 23, 2025`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Aaron Payas — partner at Hassans International Law Firm in Gibraltar, CFA charterholder, and former international footballer. From the early days of Gibraltar’s DLT licensing regime to holding a Bored Ape and co-leading one of the first fully SEC-approved token offerings, Aaron brings a unique blend of legal precision, mathematical logic, and personal passion `,
    thumb: `assets/E74_ Aaron Payas.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/104506227/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-5-23%2F402638988-44100-2-4bccdaa6dbd5c.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E74-Aaron-Payas-A-Gentleman--a-Crypto-Lawyer-and-an-ex--Footballer-e34jpdj`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 68,
    epLabel: `E73`,
    guest: `Justin Wales`,
    title: `Justin Wales Just Dropped The Crypto Legal Handbook V2`,
    date: `June 16, 2025`,
    desc: `In this episode of Beyond the Code , I’m joined once again by Justin Wales , Head of Legal for the Americas at Crypto.com and author of the Crypto Legal Handbook — now in its newly released second edition.`,
    thumb: `assets/E73_ Justin Wales (Act II).jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/104201041/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-5-16%2F402249680-44100-2-3ee07c2cb5a46.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E73-Justin-Wales-Just-Dropped-The-Crypto-Legal-Handbook-V2-e34afch`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 67,
    epLabel: `E72`,
    guest: `Joni Pirovich`,
    title: `Joni Pirovich Built Her Own AI for Crypto Lawyers (and It's Better Than ChatGPT)`,
    date: `June 09, 2025`,
    desc: `In this episode of Beyond the Code , I sit down with the brilliant and trailblazing Joni Pirovich — a lawyer, entrepreneur, and the mind behind Crystal , an AI-powered legal tool tailored for the crypto industry. We trace Joni’s remarkable journey: from growing up on a mango farm in Australia to becoming one of the most forward-thinking crypto lawyers in the space.`,
    thumb: `assets/E72_ Joni Pirovich.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/103860279/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-5-9%2F401826811-44100-2-fd47d49f88cd2.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E72-Joni-Pirovich-Built-Her-Own-AI-for-Crypto-Lawyers-and-Its-Better-Than-ChatGPT-e3402jn`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 66,
    epLabel: `E71`,
    guest: `Charlie Shrem`,
    title: `Charlie Shrem on Building Bitcoin from the Basement Up`,
    date: `May 12, 2025`,
    desc: `In this unforgettable episode of Beyond the Code , Yitzy Hammer sits down with Bitcoin OG and serial entrepreneur Charlie Shrem for a raw, unfiltered journey through the birth of Bitcoin, the collapse of early crypto infrastructure, and the deeply personal trials that shaped one of the industry's most iconic—and controversial—figures.`,
    thumb: `assets/E71_ Charlie Shrem.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/102512216/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-4-11%2F400051846-44100-2-a5856a7aa473.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E71-Charlie-Shrem-on-Building-Bitcoin-from-the-Basement-Up-e32mu4o`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 65,
    epLabel: `E70`,
    guest: `Vivek Jayaram`,
    title: `Lawyers for Innovators: Building a Creative Legal Practice with Vivek Jayaram`,
    date: `May 05, 2025`,
    desc: `What if your law firm felt more like an art studio than a courtroom? In this episode of Beyond the Code , Yitzy sits down with Vivek Jayaram , founder of Jayaram Law and one of the most creative minds in the legal space.`,
    thumb: `assets/E70_ Vivek Jayaram.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/102171136/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-4-4%2F399589183-44100-2-3962eb83b30e3.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E70-Lawyers-for-Innovators-Building-a-Creative-Legal-Practice-with-Vivek-Jayaram-e32ch20`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 64,
    epLabel: `E69`,
    guest: `Dr. Shmuel Abramzon`,
    title: `Dr. Shmuel Abramzon: Inside the Mind of Israel’s Chief Economist: Digital Assets, Regulation & the Road Ahead`,
    date: `April 30, 2025`,
    desc: `In this wide-ranging conversation, Yitzy sits down with Dr. Shmuel Abramzon , Israel’s Chief Economist at the Ministry of Finance, to unpack his unique role at the intersection of policy, macroeconomics, and innovation. They dive into the evolution of digital assets in Israel, what it really means to “regulate” crypto, and the story behind the Ministry’s landmark report on digital asset regulation. Dr.`,
    thumb: `assets/E69_ Dr. Shmuel Abramzon.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/101977105/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-30%2F399334754-44100-2-c0d386c2b8c02.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E69-Dr--Shmuel-Abramzon-Inside-the-Mind-of-Israels-Chief-Economist-Digital-Assets--Regulation--the-Road-Ahead-e326jih`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 63,
    epLabel: ``,
    guest: `Shahar Marom`,
    title: `Building Blocks and Shaping Israel’s Crypto Future with Collider VC's Managing Partner, Adam Benayoun`,
    date: `April 24, 2025`,
    desc: `On March 26, 2025,⁠ ⁠ Collider. VC ⁠⁠ hosted⁠ ⁠ Building Blocks 2025⁠⁠ , as part of ETH TLV. Our host,⁠ ⁠Yitzy Hammer⁠⁠ was invited to come and interview guests and speakers. In the last of the Building Blocks Conversations, Yitzy Hammer sat down with Adam Benayoun , managing partner at Collider, to unpack the highlights and aspirations emerging from Building Blocks 2025.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1745491221001-82114f124510a.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/101719443/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-24%2F399004458-44100-2-f71dde14b4ffc.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Building-Blocks-and-Shaping-Israels-Crypto-Future-with-Collider-VCs-Managing-Partner--Adam-Benayoun-e31unuj`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 62,
    epLabel: ``,
    guest: `Josh Schwartz`,
    title: `Josh Schwartz on Building Secure DeFi Infrastructure with FORDeFI, at #BB25`,
    date: `April 23, 2025`,
    desc: `On March 26, 2025,⁠ ⁠Collider. VC⁠⁠ hosted⁠ ⁠Building Blocks 2025⁠⁠, as part of ETH TLV. Our host,⁠ ⁠Yitzy Hammer⁠⁠ was invited to come and interview guests and speakers. Live from Building Blocks at Jaffa Port in Tel Aviv, Yitzy interviews Josh Schwartz , CEO and Co-Founder of FORDeFi , about bridging the gap between traditional finance and decentralized systems.`,
    thumb: `assets/E33 Jason Schwartz.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/101656139/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-23%2F398863326-44100-2-0e1d57fa257b9.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Josh-Schwartz-on-Building-Secure-DeFi-Infrastructure-with-FORDeFI--at-BB25-e31sq4b`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 61,
    epLabel: ``,
    guest: `Ben Samocha`,
    title: `Navigating the CryptoJungle with Ben Samocha at #BB25`,
    date: `April 22, 2025`,
    desc: `On March 26, 2025,⁠ ⁠Collider. VC⁠⁠ hosted⁠ ⁠Building Blocks 2025⁠⁠, as part of ETH TLV. Our host,⁠ ⁠Yitzy Hammer⁠⁠ was invited to come and interview guests and speakers. Live from Building Blocks at Jaffa Port in Tel Aviv, Yitzy interviews Ben Samocha , the founder of Crypto Jungle , discussing the evolution of the platform, its role in the Israeli blockchain community, and Ben's personal journey into the crypto spa`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1745267760353-295facae8cbf8.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/101585530/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-21%2F398773185-44100-2-2864c3f6467c6.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Navigating-the-CryptoJungle-with-Ben-Samocha-at-BB25-e31ql5q`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 60,
    epLabel: ``,
    guest: `Eyal Gruper`,
    title: `Eyal Gruper at #BB25 on bitcoin recovery and inheritance.`,
    date: `April 21, 2025`,
    desc: `Ever worry about what will happen to your bitcoin after you die? On March 26, 2025,⁠ ⁠ ⁠Collider.⁠ hosted⁠ ⁠ ⁠Building Blocks 2025⁠⁠⁠ , as part of ETH TLV. Our host,⁠ ⁠ ⁠Yitzy Hammer⁠ ⁠⁠ was invited to come and interview guests and speakers.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1745177905527-236c7f64fecf5.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/101538953/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-20%2F398714099-44100-2-555a43fc67414.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Eyal-Gruper-at-BB25-on-bitcoin-recovery-and-inheritance-e31p7m9`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 59,
    epLabel: ``,
    guest: `Iri Zohar`,
    title: `Iri Zohar at #BB25 on Bring's unique cashback model and how you can earn crypto while you shop!`,
    date: `April 10, 2025`,
    desc: `On March 26, 2025,⁠ ⁠ Collider. hosted⁠ ⁠ Building Blocks 2025⁠⁠ , as part of ETH TLV. Our host,⁠ ⁠ Yitzy Hammer ⁠⁠ was invited to come and interview guests and speakers. Live from Building Blocks at Jaffa Port in Tel Aviv, Yitzy sits down with Iri Zohar , CEO and founder of Bring , a crypto cashback platform that allows users to earn cryptocurrency rewards while shopping.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1744286046322-8cd66e49e85e.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/101105223/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-10%2F398161649-44100-2-b6cb52e77d45.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Iri-Zohar-at-BB25-on-Brings-unique-cashback-model-and-how-you-can-earn-crypto-while-you-shop-e31c047`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 58,
    epLabel: ``,
    guest: `Carlo D'Angelo`,
    title: `The DeFi Defender: Carlo D’Angelo on Crypto Crime, Money Mules & Building On-Chain Identity`,
    date: `April 07, 2025`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Carlo D’Angelo, the "DeFi Defender," a veteran criminal defense lawyer turned crypto law expert. Carlo shares his fascinating journey—from his early days as a public defender in Florida to becoming a key figure in the crypto legal community.`,
    thumb: `assets/E53_ Carlo D'Angelo.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/100925006/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-6%2F397930592-44100-2-7126e38fc5f9f.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/The-DeFi-Defender-Carlo-DAngelo-on-Crypto-Crime--Money-Mules--Building-On-Chain-Identity-e316g4e`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 57,
    epLabel: ``,
    guest: `Eva Beylin`,
    title: `Eva Beylin at #BB25, on The Graph, Optimism and Ethereum.`,
    date: `April 07, 2025`,
    desc: `On March 26, 2025, ⁠ ⁠Collider. VC⁠⁠ hosted ⁠ ⁠Building Blocks 2025⁠⁠ , as part of ETH TLV. Our host, ⁠ ⁠Yitzy Hammer⁠⁠ was invited to come and interview guests and speakers. Live from Building Blocks at Jaffa Port in Tel Aviv, Yitzy Hammer sits down with Eva Beylin , Board Member of Optimism and Former Director of The Graph Foundation.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1743974402608-a5ed966e7a855.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/100924660/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-6%2F397930062-44100-2-5284916a20d7c.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Eva-Beylin-at-BB25--on-The-Graph--Optimism-and-Ethereum-e316fpk`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 56,
    epLabel: ``,
    guest: `Asaf Naim`,
    title: `Asaf Naim at #BB25 on Kirobo, Intentable, and Dappable: Revolutionizing Web3 Development`,
    date: `April 04, 2025`,
    desc: `Live from Building Blocks at Jaffa Port, Yitzy Hammer chats with Asaf Naim, co-founder of Kirobo, a trailblazer in Web3 since 2018. Asaf shares his journey from a taxation accountant to a self-taught programmer, sparked by a failed Bitcoin buy in 2011 and a client’s lost crypto key in 2018. Kirobo pioneered account abstraction with "smart transactions," introducing the first undo button for crypto transfers.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1743708791175-63a0c6cbb14c7.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/100800982/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-3%2F397773772-44100-2-e8e021a7b9ef8.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Asaf-Naim-at-BB25-on-Kirobo--Intentable--and-Dappable-Revolutionizing-Web3-Development-e312n0m`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 55,
    epLabel: ``,
    guest: `Gordon Einstein`,
    title: `Gordon Einstein at #BB25 on Crypto, Tech Tuesdays Dubai, and Building Bridges with Israel’s Blockchain Ecosystem`,
    date: `April 03, 2025`,
    desc: `On March 26, 2025, ⁠Collider. VC⁠ hosted ⁠Building Blocks 2025⁠ , as part of ETH TLV. Our host, ⁠Yitzy Hammer⁠ was invited to come and interview key guests and speakers. Gordon Einstein is a pioneering crypto lawyer and founder of Dubai’s Tech Tuesdays. Gordon shares his journey from Los Angeles to Dubai, sparked by a rediscovery of law through blockchain in 2014.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1743688632550-b4dc68026d2d4.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/100785481/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-3%2F397753849-44100-2-874cffa39e188.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Gordon-Einstein-at-BB25-on-Crypto--Tech-Tuesdays-Dubai--and-Building-Bridges-with-Israels-Blockchain-Ecosystem-e3127s9`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 54,
    epLabel: ``,
    guest: `Lou Kerner`,
    title: `Lou Kerner at #BB25 on Crypto Mondays, Social Media Roots, and Israel’s Startup Nation Vibe`,
    date: `April 03, 2025`,
    desc: `On March 26, 2025, ⁠Collider. VC⁠ hosted ⁠Building Blocks 2025⁠ , as part of ETH TLV. Our host, ⁠Yitzy Hammer⁠ was invited to come and interview guests and speakers. Live from Building Blocks at Jaffa Port in Tel Aviv, Yitzy Hammer sits down with Lou Kerner, founder of Crypto Mondays.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1743707070599-c290b9490dd5.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/100799092/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-3-3%2F397771595-44100-2-0b7e422454cf9.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Lou-Kerner-at-BB25-on-Crypto-Mondays--Social-Media-Roots--and-Israels-Startup-Nation-Vibe-e312l5k`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 53,
    epLabel: ``,
    guest: `Youval Rouach`,
    title: `Live @BB25: Youval Rouach, CEO, Bits of Gold; BILS`,
    date: `March 30, 2025`,
    desc: `On March 26, 2025, Collider. VC hosted Building Blocks 2025 , as part of ETH TLV. Our host, Yitzy Hammer was invited to come and interview guests and speakers. Youval Rouach is CEO and Co-Founder of Bits of Gold , one of Israel's leading crypto currency exchanges and also of BILS , the first Israeli-shekel backed stablecoin, to be issued by Bits of Gold.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1743335483695-b7393cd47c114.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/100576713/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-2-30%2F397488677-44100-2-8a19332519d1f.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Live-BB25-Youval-Rouach--CEO--Bits-of-Gold-BILS-e30rs09`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 52,
    epLabel: `E52`,
    guest: `Tigran Gambaryan`,
    title: `How Tigran Gambaryan Deciphered Bitcoin and Survived Nigerian Prison`,
    date: `March 24, 2025`,
    desc: `Tigran Gambaryan⁠ spent 8 months in grueling conditions in a Nigerian prison. But that’s not what made him famous. Episode 52 of Beyond the Code dives into Tigran ’s incredible journey. For those of you who don’t know, Tigran started off as an IRS special agent, where he used a simple Excel spreadsheet to reverse engineer the Bitcoin blockchain and track major crypto criminals such as those responsible for the Mt.`,
    thumb: `assets/E52_ Tigran Gambaryan.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/100269421/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-2-23%2F397097962-44100-2-ee45404c25581.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E52-How-Tigran-Gambaryan-Deciphered-Bitcoin-and-Survived-Nigerian-Prison-e30iftd`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 51,
    epLabel: `E47`,
    guest: `Nadav Ellinson`,
    title: `Crypto in Your Portfolio: How Much Is Too Much? With Financial Planner Nadav Ellinson`,
    date: `March 17, 2025`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with financial planner and Blue & White Finance co-founder Nadav Ellinson to tackle one of the most debated questions in investing: How much Bitcoin (or crypto) should be in your portfolio (if any)? We discuss: ✅ The risks and rewards of allocating crypto in a long-term portfolio; ✅ Dollar Cost Averaging (DCA) vs.`,
    thumb: `assets/E47_ Nadav Ellinson.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/98259273/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-1-9%2F394578389-44100-2-fece45e1a3163.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E47-Crypto-in-Your-Portfolio-How-Much-Is-Too-Much--With-Financial-Planner-Nadav-Ellinson-e2ul4s9`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 50,
    epLabel: `E51`,
    guest: `Eran Lahav`,
    title: `How to Use AI to Make Your Legal Work 3X More Efficient with Eran Lahav, CEO of FirstRead.`,
    date: `March 17, 2025`,
    desc: `In Episode 51 of Beyond the Code , host Yitzy Hammer welcomes Eran Lahav , Co-Founder and CEO of First Read , an AI-powered legal tech platform designed to revolutionize how lawyers draft, review, and manage legal documents. In this insightful conversation, Eran shares his journey from accounting and finance to launching a cutting-edge AI tool for lawyers that improves efficiency and streamlines legal workflows.`,
    thumb: `assets/E51_ Eran Lahav.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/99978294/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-2-17%2F396726998-44100-2-2b749ddce0774.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E51-How-to-Use-AI-to-Make-Your-Legal-Work-3X-More-Efficient-with-Eran-Lahav--CEO-of-FirstRead-e309jjm`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 49,
    epLabel: `E50`,
    guest: `Amanda Wick`,
    title: `Web3 Beyond Crypto Bros with Amanda Wick | Women in Crypto`,
    date: `March 10, 2025`,
    desc: `Episode Summary: In this milestone 50th episode of Beyond the Code , host Yitzy Hammer sits down with Amanda Wick, CEO and founder of the Association for Women in Crypto, for an expansive conversation that goes far beyond the blockchain.`,
    thumb: `assets/E50_ Amanda Wick.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/99603817/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-2-9%2F396258994-44100-2-5c555e8e48336.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Ep--50-Web3-Beyond-Crypto-Bros-with-Amanda-Wick--Women-in-Crypto-e2vu5t9`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 48,
    epLabel: `E49`,
    guest: `Bentzi Rabi`,
    title: `Second Mover Advantage: Bentzi Rabi on Utila’s Crypto Play`,
    date: `March 03, 2025`,
    desc: `In Episode 49 of Beyond the Code, Bentzi Rabi , CEO of Utila , shares his fascinating journey from an Israeli intelligence unit to founding an enterprise-grade crypto operations platform. Discover how a chance encounter at a Bitcoin embassy chess club sparked his crypto passion, leading him to challenge giants like Fireblocks with Utila’s focus on flexibility, on-chain innovation, and stablecoin payments.`,
    thumb: `assets/E49_ bentzi rabi.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/99246287/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-2-2%2F395809289-44100-2-fb2bc864c4dc4.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E49-Second-Mover-Advantage-Bentzi-Rabi-on-Utilas-Crypto-Play-e2vj8of`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 47,
    epLabel: `E48`,
    guest: `Dr. Jimmie Lenz`,
    title: `Dr. Jimmie Lenz on Crypto, AI, GenZ, DA@D, the US Regulatory Climate, and more.`,
    date: `February 25, 2025`,
    desc: `Last week, Yitzy attended Coindesk's premier event in Hong Kong, #ConsensusHK, where he livestreamed Beyond the Code episodes with leading innovators in the blockchain arena (more on that in the coming weeks). This week, Yitzy is back with the 48th episode of BTC! In this episode, Yitzy connects with Dr. Jimmie Lenz, a trailblazer in the crypto space and FinTech educator at Duke University. They explore Dr.`,
    thumb: `assets/E48_ Dr. Jimmie Lenz.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/98989887/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-1-25%2F395491932-44100-2-f1241c990a18c.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/E48-Dr--Jimmie-Lenz-on-Crypto--AI--GenZ--DAD--the-US-Regulatory-Climate--and-more-e2vbebv`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 46,
    epLabel: ``,
    guest: `Tom Teman`,
    title: `Inside Ethereum: Tom Teman on Account Abstraction and the Future of Wallets`,
    date: `February 03, 2025`,
    desc: `In this episode of Beyond the Code, Yitzy sits down with Tom Teman from the Ethereum Foundation to explore his path from early crypto days to shaping the future of wallets through account abstraction. Tom details his journey founding Portis, getting acquired by ShapeShift, and eventually joining Kraken—before landing at the Ethereum Foundation.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1738070192590-a038681da0d02.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/97679199/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-0-28%2F393856254-44100-2-198053bf8dbfe.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Inside-Ethereum-Tom-Teman-on-Account-Abstraction-and-the-Future-of-Wallets-e2u3ecv`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 45,
    epLabel: ``,
    guest: `Jonathan Caras`,
    title: `Memes on Steroids: The Rise of Meme Coins with Jonathan Caras`,
    date: `January 28, 2025`,
    desc: `In this special episode of Beyond the Code , Yitzy Hammer welcomes back Jonathan Caras for a lively discussion on the rise of meme coins and their impact on the crypto landscape. From the evolution of token issuance—Bitcoin, ICOs, DeFi Summer—to the chaotic yet fascinating world of meme tokens like $TRUMP Coin and $MELANIA Token, Jonathan unpacks how these tokens sidestep traditional expectations and regulatory hurdl`,
    thumb: `assets/E98_ Jonathan Benton.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/97690826/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-0-28%2F393870970-44100-2-f8b1e83b85fcc.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Memes-on-Steroids-The-Rise-of-Meme-Coins-with-Jonathan-Caras-e2u3poa`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 44,
    epLabel: ``,
    guest: `Eylon Aviv`,
    title: `Inside Israel’s Crypto VC Scene: A Deep Dive with Eylon Aviv of Collider VC`,
    date: `January 27, 2025`,
    desc: `In this episode, Yitzy sits down with Eylon Aviv , a partner at Collider.VC , Israel’s leading crypto-centric venture capital fund. Eylon shares his journey from early days at tech unicorn IronSource to becoming a driving force in Israel’s crypto ecosystem.`,
    thumb: `assets/E44_ Eylon Aviv.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/97596013/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-0-26%2F393752490-44100-2-4ee3dce23d885.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Inside-Israels-Crypto-VC-Scene-A-Deep-Dive-with-Eylon-Aviv-of-Collider-VC-e2u0t5d`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 43,
    epLabel: ``,
    guest: `Hester Peirce`,
    title: `Crypto Mom to Crypto Stepmom: SEC Commissioner Hester Peirce on SEC Challenges and Opportunities`,
    date: `January 20, 2025`,
    desc: `In this episode of Beyond the Code , SEC Commissioner Hester Peirce , affectionately referred to within the cryptoverse as "Crypto Mom," joins Yitzy to discuss the SEC’s evolving approach to cryptocurrency and innovation.`,
    thumb: `assets/E43_ Hester Peirce.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/97236002/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-0-18%2F393306112-44100-2-091f33a9a2768.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Crypto-Mom-to-Crypto-Stepmom-SEC-Commissioner-Hester-Peirce-on-SEC-Challenges-and-Opportunities-e2tltj2`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 42,
    epLabel: ``,
    guest: `Noah Perlman`,
    title: `With Great Power Comes Great Responsibility: Noah Perlman on Binance, Regulation, and the Road Ahead`,
    date: `January 13, 2025`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Noah Perlman , Chief Compliance Officer at Binance, to explore the intricate balance of power, responsibility, and innovation at the world’s largest crypto exchange. Noah reflects on his journey from a federal prosecutor and DEA counsel to leading the compliance efforts of the one of the most important institutions in crypto.`,
    thumb: `assets/E42_ Noah Perlman.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/96919655/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-0-11%2F392911365-44100-2-461baf31cf22d.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/With-Great-Power-Comes-Great-Responsibility-Noah-Perlman-on-Binance--Regulation--and-the-Road-Ahead-e2tc8l7`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 41,
    epLabel: ``,
    guest: `Ouriel Ohayon`,
    title: `Trolling for Truth in the War of Words and Building the Best Crypto Wallet on the Planet, with ZenGo’s Ouriel Ohayon`,
    date: `December 23, 2024`,
    desc: `In this episode of Beyond the Code, Yitzy Hammer sits down with Ouriel Ohayo n, CEO and founder of ZenGo , to explore the cutting-edge innovations behind the world’s most secure crypto wallet. Ouriel shares the journey from discovering crypto to building a wallet that eliminates the pain points of seed phrases, leverages multi-party computation (MPC) technology, and prioritizes user security and simplicity.`,
    thumb: `assets/E41_ ouriel ohayon.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/96179564/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-11-23%2F391995616-44100-2-11826f01939a.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Trolling-for-Truth-in-the-War-of-Words-and-Building-the-Best-Crypto-Wallet-on-the-Planet--with-ZenGos-Ouriel-Ohayon-e2slltc`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 40,
    epLabel: ``,
    guest: `Prof. Edward Lee`,
    title: `Prof. Edward Lee on The Resurgence of NFTs and AI’s Impact on Copyright Law`,
    date: `December 17, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Professor Edward Lee, a leading expert in intellectual property, copyright law, and emerging technologies. Professor Lee, author of Creators Take Control , dives into the fascinating world of NFTs, AI, and their legal and cultural implications.`,
    thumb: `assets/E40_ prof. edward lee.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/95939347/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-11-17%2F391692812-44100-2-d83b80d06d27.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Prof--Edward-Lee-on-The-Resurgence-of-NFTs-and-AIs-Impact-on-Copyright-Law-e2sebaj`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 39,
    epLabel: ``,
    guest: `Ofir Eliasi`,
    title: `Ofir Eliasi: Revolutionizing Wallet Infrastructure with Account Abstraction in Web3`,
    date: `December 11, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Ofir Eliasi , founder of Borsa , to discuss his journey as a serial entrepreneur and blockchain innovator. Ofir shares his background, from early days in the 8200 unit of the Israeli army to leading development at major tech companies and startups, including his work on groundbreaking blockchain projects since 2017.`,
    thumb: `assets/E39_ Ofir Eliasi.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/95659079/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-11-11%2F391367358-44100-2-755d2750e316e.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Ofir-Eliasi-Revolutionizing-Wallet-Infrastructure-with-Account-Abstraction-in-Web3-e2s5pk7`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 38,
    epLabel: ``,
    guest: `Nick Furneaux`,
    title: `Nick Furneaux on Investigating Cryptocurrencies and his new book, ‘There is No Such Thing as Crypto Crime’.`,
    date: `November 25, 2024`,
    desc: `In Episode 38, Yitzy interviews Nick Furneaux , a pioneer in cryptocurrency investigations and digital forensics. They discuss the realities of crypto crime, the evolution of investigations, and the importance of understanding cryptocurrency for law enforcement.`,
    thumb: `assets/E38_ Nick Furneaux.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/94901171/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-10-24%2F390403205-44100-2-9f7067ec68901.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Nick-Furneaux-on-Investigating-Cryptocurrencies-and-his-new-book--There-is-No-Such-Thing-as-Crypto-Crime-e2relfj`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 37,
    epLabel: ``,
    guest: `Mati Greenspan Reveals`,
    title: `Mati Greenspan Reveals What the Future Holds for Bitcoin, Mining, and DeFi`,
    date: `November 19, 2024`,
    desc: `What’s next for Bitcoin? Yitzy Hammer and Quantum Economics ' Mati Greenspan dive into the seismic shifts shaping the crypto world in the wake of Trump's election and the US's new stance on crypto. From Bitcoin’s rise as a nation-state reserve asset to the untapped potential of DeFi, this episode explores the forces driving blockchain innovation.`,
    thumb: `assets/E37 Mati Greenspan.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/94615882/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-10-18%2F390052488-44100-2-242b79e639801.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Mati-Greenspan-Reveals-What-the-Future-Holds-for-Bitcoin--Mining--and-DeFi-e2r5usa`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 36,
    epLabel: ``,
    guest: `JP Thor`,
    title: `JP Thor on ThorChain and the Power of Memes`,
    date: `November 05, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy Hammer sits down with JP Thor⁠⁠ , the visionary founder behind ⁠⁠ThorChain . From his roots in remote Australia to his career as a fighter and bomber pilot, JP shares his remarkable journey into decentralized finance and the creation of ThorChain , a groundbreaking cross-chain liquidity protocol .`,
    thumb: `assets/E36 JP Thor.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/93968676/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-10-4%2F389252050-44100-2-90b76dbc67a62.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/JP-Thor-on-ThorChain-and-the-Power-of-Memes-e2qi6r4`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 35,
    epLabel: ``,
    guest: `Jake Brukhman`,
    title: `Jake Brukhman on CoinFund and Crypto Investing`,
    date: `October 30, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy Hammer sits down with ⁠Jake Brukhman⁠ , founder and CEO of ⁠CoinFund⁠ , to explore the evolution of crypto investing. Jake shares his journey from discovering Bitcoin in 2011 to launching one of the first crypto-native investment firms, CoinFund, in 2015.`,
    thumb: `assets/E79_ Jake Adelstein.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/93761903/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-9-30%2F388996595-44100-2-44b9b8498587f.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Jake-Brukhman-on-CoinFund-and-Crypto-Investing-e2qbstf`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 34,
    epLabel: ``,
    guest: `Amanda Tuminelli`,
    title: `Defending DeFi: Amanda Tuminelli on the Fight for Fair Crypto Laws and Policies`,
    date: `September 30, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Amanda Tuminelli , Chief Legal Officer at the DeFi Education Fund , to explore the critical legal battles shaping the future of decentralized finance.`,
    thumb: `assets/E50_ Amanda Wick.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/92384778/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-8-30%2F387287427-44100-2-ea212bb6d6b89.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Defending-DeFi-Amanda-Tuminelli-on-the-Fight-for-Fair-Crypto-Laws-and-Policies-e2p1s2a`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 33,
    epLabel: ``,
    guest: `Jason Schwartz`,
    title: `Crypto Taxation, DAOs, and the Future of Decentralization with Jason Schwartz`,
    date: `September 10, 2024`,
    desc: `In this episode of ⁠ Beyond the Code ⁠, Yitzy sits down with ⁠ Jason Schwartz⁠ , tax partner and co-head of ⁠ Fried Frank⁠ ’s Digital Assets and Blockchain Practice, for a lively discussion on crypto taxation, DAOs (Decentralized Autonomous Organizations), and the future of decentralization.`,
    thumb: `assets/E26 Jason Gottlieb.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/91514226/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-8-10%2F386095351-44100-2-08d397f75d599.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Crypto-Taxation--DAOs--and-the-Future-of-Decentralization-with-Jason-Schwartz-e2o79ti`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 32,
    epLabel: ``,
    guest: `Joseph Page`,
    title: `Solana, AI, and Decentralized Infrastructure: Joseph Page’s Investment Journey`,
    date: `September 04, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Joseph Page , founder of the Web3-focused venture capital firm Strange Quark . Joseph shares his unique journey from his roots in Honduras to studying and competing in ping pong in Taiwan, and ultimately moving to Israel, where he became a key player in the crypto world.`,
    thumb: `assets/E32 Joseph Page.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/91271747/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-8-4%2F385796989-44100-2-4957f638718a5.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Solana--AI--and-Decentralized-Infrastructure-Joseph-Pages-Investment-Journey-e2nvt43`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 31,
    epLabel: ``,
    guest: `Moish Peltz`,
    title: `A Journey Down the Ape Hole and Into U.S. Politics with Moish Peltz`,
    date: `August 15, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy is joined by Moish Peltz , a partner at Falcon Rappaport & Berkman PLLC , co-host of the Block & Order podcast , and a true OG in the world of crypto law. Moish shares his fascinating journey from his early days in the IP and tech law sectors to becoming a key figure in the crypto space, diving deep into the concept of being a "crypto degen lawyer." The conversation kicks of`,
    thumb: `assets/E31 Moish Peltz.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/90478349/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-7-15%2F384822642-44100-2-d5826372592f3.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/A-Journey-Down-the-Ape-Hole-and-Into-U-S--Politics-with-Moish-Peltz-e2n7mad`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 30,
    epLabel: ``,
    guest: `Flavia Naves`,
    title: `Wyoming's Stable Token Future with Flavia Naves`,
    date: `August 07, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy sits down with Flavia Naves to explore her remarkable journey from Brazil to the US, culminating in her influential role on the Wyoming Stable Token Commission . Flavia shares her unique experiences, including her pivotal role as General Counsel at Circle, where she navigated the complexities of the USDC stablecoin and the challenges of the Silicon Valley Bank crisis.`,
    thumb: `assets/E30 Flavia Naves.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/90172175/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-7-7%2F384448102-44100-2-7c84ad078ce3d.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Wyomings-Stable-Token-Future-with-Flavia-Naves-e2mubaf`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 29,
    epLabel: ``,
    guest: `Brian Frye & Jonathan Mann`,
    title: `Is this song a 'security'? Brian Frye and Jonathan Mann sued the SEC to find out.`,
    date: `August 01, 2024`,
    desc: `Description: In this special episode of Beyond the Code , host Yitzy welcomes back previous guests Brian L. Frye and Jason Gottlieb, along with new guest Jonathan Mann , to discuss their recent lawsuit against the SEC.`,
    thumb: `assets/E98_ Jonathan Benton.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/89925113/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-7-1%2F384143878-44100-2-98301bd483357.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Is-this-song-a-security--Brian-Frye-and-Jonathan-Mann-sued-the-SEC-to-find-out-e2mmq1p`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 28,
    epLabel: ``,
    guest: `Erin West`,
    title: `Fighting Crypto Crime with Erin West`,
    date: `July 16, 2024`,
    desc: `In this riveting episode of Beyond the Code, Yitzy is joined by Erin West , the dynamic Deputy District Attorney from Santa Clara County. Erin takes us on a deep dive into the murky waters of cybercrime, revealing the chilling realities of modern digital scams.`,
    thumb: `assets/E28 Erin West.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/89257418/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-6-15%2F383239399-44100-2-621d896ed5065.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Fighting-Crypto-Crime-with-Erin-West-e2m2e0a`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 27,
    epLabel: ``,
    guest: `Jamie Bartlett`,
    title: `Dark Net to Crypto Scam: Jamie Bartlett’s Tales from the Trenches`,
    date: `July 08, 2024`,
    desc: `Episode Description: In this riveting episode of Beyond the Code, Yitzy welcomes Jamie Bartlett, acclaimed author and technology journalist, to explore the enigmatic world of the "Crypto Queen" and the OneCoin scandal. Jamie shares his in-depth investigation into Dr. Ruja Ignatova’s infamous Ponzi scheme, providing listeners with an insider’s perspective on one of the biggest scams in cryptocurrency history.`,
    thumb: `assets/E2 7Jamie Bartlett.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/88783384/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-6-3%2F382325026-44100-2-69c740e4efd89.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Dark-Net-to-Crypto-Scam-Jamie-Bartletts-Tales-from-the-Trenches-e2ljv2o`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 26,
    epLabel: ``,
    guest: `Jason Gottlieb`,
    title: `Inside the Crypto Courtroom with Jason Gottlieb`,
    date: `July 03, 2024`,
    desc: `Summary - In this episode of "Beyond the Code," Yitzy hosts J ason Gottlieb , partner and head of the digital assets department at Morrison Cohen , for an insightful discussion on the complexities and challenges of crypto regulation and litigation.`,
    thumb: `assets/E26 Jason Gottlieb.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/88755740/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-6-2%2F382267039-44100-2-dbb046f6416dc.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Inside-the-Crypto-Courtroom-with-Jason-Gottlieb-e2lj42s`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 25,
    epLabel: ``,
    guest: `Alex Davis`,
    title: `Unlocking Real World Assets: A Deep Dive with Alex Davis of Mavryk`,
    date: `June 26, 2024`,
    desc: `In this episode of Beyond the Code , host Yitzy Hammer engages in an enlightening conversation with Alex Davis , founder of Mavryk Dynamics, about the fascinating world of Real World Assets (RWAs) and their tokenization. This episode offers a comprehensive exploration of how blockchain technology is revolutionizing asset ownership and investment.`,
    thumb: `assets/E96_ Russ Davis.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/88478775/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-5-26%2F381686904-44100-2-9a1df48b92b1a.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Unlocking-Real-World-Assets-A-Deep-Dive-with-Alex-Davis-of-Mavryk-e2laljn`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 24,
    epLabel: ``,
    guest: `Arye Schreiber`,
    title: `Arye Schreiber: Revolutionizing Data Privacy Ops with Armadillex (AI)`,
    date: `June 16, 2024`,
    desc: `Arye Schreiber , an Anglo-Israeli privacy lawyer and the founder of Armadillex , discusses the challenges faced by data privacy professionals and how his platform aims to address them. Armadillex is an AI-powered platform that helps organizations manage their data privacy relationships and provides business insights based on data processing agreements (DPAs).`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1718544535872-299ebf096ec55.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/88084426/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-5-16%2F380810439-44100-2-29b5552dbff43.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Arye-Schreiber-Revolutionizing-Data-Privacy-Ops-with-Armadillex-AI-e2kukga`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 23,
    epLabel: ``,
    guest: `Prof. ⁠Ilan Alon⁠: Crypto's Impact on Gl`,
    title: `Prof. ⁠Ilan Alon⁠: Crypto's Impact on Globalization, Global Economics, and Governance`,
    date: `June 10, 2024`,
    desc: `In this episode, Yitzy discussed the impact of cryptocurrencies on globalization, global economics, and governance with Prof. ⁠Ilan Alon⁠ , dean of the School of Economics at the College of Management. We also explored regulatory challenges and the role of the United States in the crypto industry.`,
    thumb: `assets/E40_ prof. edward lee.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/87846637/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-5-10%2F380264875-44100-2-3aa0492bb4a6d.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Prof--Ilan-Alon-Cryptos-Impact-on-Globalization--Global-Economics--and-Governance-e2knc9d`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 22,
    epLabel: ``,
    guest: `Ari Redbord`,
    title: `Shaping Policy and Fighting Crime: A Conversation with Ari Redbord of TRM Labs`,
    date: `May 20, 2024`,
    desc: `In this episode of Beyond the Code , Yitzy Hammer sits down with Ari Redbord , the Global Head of Policy at TRM Labs, to discuss the intersection of cryptocurrency and national security. Ari shares his journey from a federal prosecutor focusing on local crime and national security cases to his current role at TRM Labs .`,
    thumb: `assets/E99_ Ari Redbord.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/86931022/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-4-20%2F73ceaf79-a19f-945f-2a39-398c4a4f0bc7.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Shaping-Policy-and-Fighting-Crime-A-Conversation-with-Ari-Redbord-of-TRM-Labs-e2jre4e`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 21,
    epLabel: ``,
    guest: `Tal Mimran`,
    title: `AI Warfare with Tal Mimran: Navigating Ethics and Law in the IDF`,
    date: `May 02, 2024`,
    desc: `In this enlightening episode of "Beyond the Code," Yitzy hosts T al Mimran , a professor of international law and a pioneer in the field of military legal advisory. Together, they delve into the complex world of artificial intelligence in military operations, focusing on the IDF's use of AI and its implications under international law.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1714652289623-dfab69a037795.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/86217259/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-4-2%2F4bac4ac7-4949-ce1a-5c8a-46e474c79c78.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/AI-Warfare-with-Tal-Mimran-Navigating-Ethics-and-Law-in-the-IDF-e2j5l3b`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 20,
    epLabel: ``,
    guest: `Justin Wales`,
    title: `Justin Wales: The Crypto Legal Handbook and Being A Nice Guy`,
    date: `May 01, 2024`,
    desc: `Justin Wales is Head of Legal For The Americas at Crypto.com. He is also something of an OG in the crypto legal world and recently published his first and greatest work yet: "The Crypto Legal Handbook" - an excellent guide for anyone curious about the intricate world of crypto regulations in the US. Wheather your a nube or an OG, this book has something for everyone.`,
    thumb: `assets/E73_ Justin Wales (Act II).jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/86163609/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-4-1%2F5d66ed98-a646-1534-473e-eb3fad954971.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Justin-Wales-The-Crypto-Legal-Handbook-and-Being-A-Nice-Guy-e2j40mp`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 19,
    epLabel: ``,
    guest: `Alon Goren`,
    title: `Alon Goren: Blockchain OG Investor and Entrepreneur (AKA Punk Apestrong)`,
    date: `April 16, 2024`,
    desc: `Alon is a legit crypto OG investor - having made over 30 crypto-centric investments through multiple funds. He is also an ape...his Bored Ape Yacht Club alter-ego (BAYC #5011) is called Punk Apestrong and is a perfect example of the IP creativity spawned by NFTs and the BAYC in particular. Love to see it! Make sure to follow him on X , LinkedIn and check out his latest fund - dgb .`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1713243684659-c25c56c40eb04.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/85478955/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-3-16%2F46472b0a-075a-68e1-12dd-a74ffe74a0e9.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Alon-Goren-Blockchain-OG-Investor-and-Entrepreneur-AKA-Punk-Apestrong-e2if43b`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 18,
    epLabel: ``,
    guest: `Teresa Carballo`,
    title: `Why Panama? With Crypto Lawyer Teresa Carballo`,
    date: `April 08, 2024`,
    desc: `Teresa is a Panamanian lawyer and co-founder of the Panamanian law practice, Pacífica Legal . She is also a mother of 2 and an avid horse rider 🐎. In this episode, Teresa and I discussed her journey into crypto law and why Panama has become a popular jurisdiction for companies with crypto products.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1712582006899-8677cb0fc36ae.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/85130324/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-3-8%2Ffefd1e9d-901f-3dd3-8325-384ab2b60e72.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Why-Panama--With-Crypto-Lawyer-Teresa-Carballo-e2i4fkk`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 17,
    epLabel: ``,
    guest: `Freeman Lewin`,
    title: `Freeman Lewin: A Lawyer, a Scholar and an Entrepreneur.`,
    date: `April 03, 2024`,
    desc: `Freeman Lewin is a New York-based [ex]-attorney and entrepreneur, with a specialization in blockchain and crypto-assets. He has founded (in the past 12-months alone) several technology start-ups and is passionate about building tools to solve big complex problems.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1712129079647-6289d484d3139.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/84902402/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-3-3%2Ff813b0dc-9f8f-4cbd-0a56-61fd376faa65.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Freeman-Lewin-A-Lawyer--a-Scholar-and-an-Entrepreneur-e2hth22`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 16,
    epLabel: ``,
    guest: `Zada Haj`,
    title: `Breaking Barriers: Zada Haj's Entrepreneurial Journey as an Arab Woman in Israel`,
    date: `March 28, 2024`,
    desc: `Join us on Beyond the Code as we welcome Zada Haj , a visionary entrepreneur who defied odds to forge her own path in the tech world. From humble beginnings in Kfar Yasif village to co-founding the DANA Accelerator and Future Holders , empowering women in desert tech, Zada's journey is a testament to resilience and innovation.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1711624308380-d75a3d2dbfd74.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/84658732/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-2-28%2F937ac60d-7e6a-c0e7-80bf-b031cfd0711f.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Breaking-Barriers-Zada-Hajs-Entrepreneurial-Journey-as-an-Arab-Woman-in-Israel-e2hm33c`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 15,
    epLabel: ``,
    guest: `Ariel Givner`,
    title: `From Trading Floors to Legal Wars: The Crypto Journey of Ariel Givner`,
    date: `March 14, 2024`,
    desc: `Episode Summary: In this captivating episode of Beyond the Code, Yitzy welcomes Ariel Givner, a trailblazing attorney in the cryptocurrency sphere and the legal mind behind Givner Law PLC. Arielle shares her unconventional journey from stock trading to founding her own law practice, diving deep into the worlds of cryptocurrency, NFTs, and the legal challenges that come with them.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1710424402998-540ded1942554.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/84031926/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-2-14%2F67a6ce45-672d-e1a0-50f7-1237833a9e83.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/From-Trading-Floors-to-Legal-Wars-The-Crypto-Journey-of-Ariel-Givner-e2h2uvm`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 14,
    epLabel: ``,
    guest: `Hernan Arber`,
    title: `Hernan Arber: Reinventing the Music Supply Chain`,
    date: `March 10, 2024`,
    desc: `Hernan Arber is the CEO of Soundwork, Founder of Arber Tech, and Host of the Web3 Creators Podcast. He is an experienced Software team leader and strategic advisor specializing in web3, NFTs, and blockchain technologies. In this episode, we talk about the vibrant tech and web3 ecosystem in Israel, building [and getting burned] in the blockchain industry.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1710093297906-32b58adb4beda.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/83829787/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-2-10%2F58a92017-c8f8-5794-8b06-bbd135daa06d.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Hernan-Arber-Reinventing-the-Music-Supply-Chain-e2gspir`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 13,
    epLabel: ``,
    guest: `Dr. Max Li`,
    title: `Dr. Max Li - Oortech and the AI-Cloud-Chain Revolution`,
    date: `January 08, 2024`,
    desc: `I had the distinct pleasure of interviewing Columbia University's Dr. Max Li - a brilliant electrical engineer, entrepreneur, and investor, who is also the CEO and Co-Founder of Oort (https://www.oortech.com/), an AI-powered decentralized cloud, with optimal privacy features and at a fraction of the cost (literally)! What the OORT team are doing is truly revolutionary! I suggest you tune in.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1704745371131-30d5a71fef22c.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/80986910/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2024-0-8%2F906916ba-1b63-bd9e-64dd-2a321593a627.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Dr--Max-Li---Oortech-and-the-AI-Cloud-Chain-Revolution-e2e61au`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 12,
    epLabel: ``,
    guest: `Hillel Fuld`,
    title: `Hillel Fuld's future: drone delivery, mixed reality surgeries and NO MORE iPhones!!! WHAT?!?!`,
    date: `September 28, 2023`,
    desc: `I've known Hillel for years and have been eager to bring him on as a BTC guest. As a strong advocate for tech generally, his perspective on what the future holds for emerging technology sectors is crucial. As always, his perspective was fresh and insightful. In this episode, we discussed the tech of the future and what's in store for us.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1695850141376-94463d1a7c238.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/76473955/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-8-27%2F348809158-44100-2-8aa5182b671ac.m4a`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Hillel-Fulds-future-drone-delivery--mixed-reality-surgeries-and-NO-MORE-iPhones----WHAT-e29sa53`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 11,
    epLabel: ``,
    guest: `Dr. Oliver Scherenberg`,
    title: `Legalpreneur, Dr. Oliver Scherenberg on Web3Lex, setting legal precedents in AI and making web3 legal knowledge more accessible`,
    date: `September 21, 2023`,
    desc: `Dr. Oliver Scherenberg is an IP attorney with over 15 years of experience in licensing and monetization. In addition to his legal practice, he is the founder of web3lex , a search engine for web3 rules and laws, powered by web3 lawyers from all over the world. In this episode, we discussed web3lex, as well as [what else] - crypto, AI, IP and more.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1695290154866-3942bc66553f1.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/76182850/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-8-21%2F347924168-44100-2-b3b6a07723cfc.m4a`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Legalpreneur--Dr--Oliver-Scherenberg-on-Web3Lex--setting-legal-precedents-in-AI-and-making-web3-legal-knowledge-more-accessible-e29jds2`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 10,
    epLabel: ``,
    guest: `Jacob Robinson`,
    title: `Beyond the Law of Code with Canadian Lawyer and Podcast Host, Jacob Robinson`,
    date: `September 18, 2023`,
    desc: `When I decided to expand my legal practice into blockchain regulatory compliance, one of the most valuable resources available was Jacob Robinson's blockchain legal podcast, the Law of Code. Now on its 115th episode, Jacob's podcast has featured anyone and everyone in the blockchain legal and regulatory space, including SEC Commissioner, Hester Pierce, Coinbase's CLO, Paul Grewal, and Yours Truly (Episode #58 😉).`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1695026011412-ad563d79ef2ff.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/76037933/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-8-18%2F347473427-44100-2-b93c623924c3b.m4a`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Beyond-the-Law-of-Code-with-Canadian-Lawyer-and-Podcast-Host--Jacob-Robinson-e29f0bd`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 9,
    epLabel: ``,
    guest: `John Keh`,
    title: `From Alameda's Trading Desks to Tomorrow's AI & NFTs: A Crypto Odyssey with John Keh`,
    date: `August 31, 2023`,
    desc: `In this episode, I sit down with John Keh, a pioneer in the Web3 space and a key player in the cryptocurrency industry. As one of the first employees at Alameda Research, the legendary cryptocurrency trading firm founded by Sam Bankman-Fried, John has unique insights into crypto, NFTs, and AI.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1693484523200-abd4a613e68a3.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/75304014/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-7-31%2Fba27eb77-9dab-c6c2-831a-8586d1d00edd.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/From-Alamedas-Trading-Desks-to-Tomorrows-AI--NFTs-A-Crypto-Odyssey-with-John-Keh-e28ojke`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 8,
    epLabel: ``,
    guest: `Amit Levine`,
    title: `Crypto Crime with Ex-Prosecutor turned Binance Investigator Amit Levin`,
    date: `August 21, 2023`,
    desc: `Amit used to be the Head of the Economics Department at the Cyber Unit of Israel's State Attorney before leaving to join the world's largest crypto exchange, Binance, as a Special Investigator. In this episode, we discuss how blockchain is used by some criminals to evade taxes and local authorities and how that is about to change [and already has for the most part].`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1692609368666-ee320e05b64d.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/74867683/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-7-21%2Fa464c062-3b86-7bea-c0fe-58640d9430c7.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Crypto-Crime-with-Ex-Prosecutor-turned-Binance-Investigator-Amit-Levin-e28b9h3`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 7,
    epLabel: ``,
    guest: `Jesse Hynes`,
    title: `Chain Reaction: Cryptocurrency's Promise for Positive Change (With Jessica Salama)`,
    date: `July 17, 2023`,
    desc: `This Tuesday I will be giving over a workshop at ETHcc (the Ethereum Community Conference) in Paris. The workshop is titled "How web3 tools can be Used for Charity and Impact." I will be drawing on some of my experiences working with non-profits to raise money in crypto and also more generally about how blockchain can be leveraged to make the world a better place.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1689544840277-19ea8736686e4.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/73480928/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-6-16%2F339532741-44100-2-7f0764ae99f46.m4a`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Chain-Reaction-Cryptocurrencys-Promise-for-Positive-Change-With-Jessica-Salama-e270v90`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 6,
    epLabel: ``,
    guest: `Franklin Graves`,
    title: `Who does AI output belong to? With IP & Media Law Attorney Franklin Graves`,
    date: `July 11, 2023`,
    desc: `In this episode, I was joined by IP, tech, and media law expert, Franklin Graves . We talked focused on two super-interesting and relevant topics: 1. A recent lawsuit filed against Meta (including Instagram, Facebook), Snap Inc., ByteDance and TikTok, and Alphabet Inc./Google/YouTube, about the mental health impacts of social media on youth. Franklin wrote a blog post about this on his blog, Creator Economy Law .`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1689080343414-c4774cbcac63c.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/73270869/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-6-11%2F0023db0a-0dc0-05d1-a73c-5e75479f0254.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Who-does-AI-output-belong-to--With-IP--Media-Law-Attorney-Franklin-Graves-e26qi4l`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 5,
    epLabel: ``,
    guest: `Prof. Scott Kominers`,
    title: `Market Design: Bridging Tech and Humanity with Prof. Scott Kominers`,
    date: `June 04, 2023`,
    desc: `This episode is long overdue (we recorded 8+ weeks ago!) but I enjoyed talking to Scott so much that we recorded for almost 2 hours - hence, editing was a nightmare! Scott is brilliant and has so many varied interests that I could have gone on talking to him all day.`,
    thumb: `assets/E40_ prof. edward lee.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/71570879/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-5-4%2F999f7d60-43ad-1087-b00d-5f44a6fc9b7e.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Market-Design-Bridging-Tech-and-Humanity-with-Prof--Scott-Kominers-e256lvv`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 4,
    epLabel: ``,
    guest: `Avishai Ostrin`,
    title: `AI & Privacy Unmasked with Avishai Ostrin - Balancing Innovation and Confidentiality`,
    date: `April 30, 2023`,
    desc: `Since the GDPR came into force in 2018, privacy has become an integral part of any technology, new or old and AI is no different. In this episode, I discuss some of the important privacy aspects of ChatGPT and other AI tools, together with Avishai Ostrin , Director of Advisory Services at Privacy Team . This isn't the first time Avishai and I have combined forces.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1682861647409-2b61b2a1f8db5.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/69541719/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-3-30%2Fd59f4012-172e-ecaf-828d-5ca03c05fa0a.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/AI--Privacy-Unmasked-with-Avishai-Ostrin---Balancing-Innovation-and-Confidentiality-e238ocn`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 3,
    epLabel: ``,
    guest: `Zach Abramowitz`,
    title: `Zach Abramowitz: Legaltech and AI`,
    date: `March 27, 2023`,
    desc: `In this episode, I had the pleasure of interviewing Zach Abramowitz , an expert in the world of legal technology. We dove deep into the fascinating realm of #LegalTech and discussed how generative AI is poised to revolutionize the legal profession. helps law firms and law departments identify and partner with the most cutting-edge technology companies.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_episode/36761908/36761908-1679900084007-3d7cb8572f14.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/67385375/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-2-27%2F5dd5e7db-482b-48e0-025a-d22b8ab5fa26.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Zach-Abramowitz-Legaltech-and-AI-e216uiv`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 2,
    epLabel: ``,
    guest: `Dr. Hadar Jabotinsky`,
    title: `Does AI pose a threat to academic literature and why plagiarism is sometimes ok - with Brian Frye.`,
    date: `March 09, 2023`,
    desc: `Brian L. Frye is a law professor at the University of Kentucky. His research focuses on intellectual property and charity law, especially in relation to artists and arts organizations. Professor Frye is also an artist and filmmaker and just a really interesting dude. Among other works, he produced the documentary 'Our Nixon' (2013), which was broadcast by CNN and opened theatrically nationwide.`,
    thumb: `https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_episode400/36761908/36761908-1678370973522-84003341be4ee.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/66240873/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-2-9%2F55252526-bfdb-d2e8-2883-a38f7cf611c9.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Does-AI-pose-a-threat-to-academic-literature-and-why-plagiarism-is-sometimes-ok---with-Brian-Frye-e2040t9`,
    apple: `#`,
    youtube: `#`,
  },
  {
    id: 1,
    epLabel: ``,
    guest: `Jonathan Caras`,
    title: `Lessons in AI and Ethics from a Crypto OG - Jonathan Caras of Levana Protocol`,
    date: `February 27, 2023`,
    desc: `In this episode, I interview Jonathan Caras, Head of Comms at Levana Protocol and previously a member of the LFG (Luna Foundation Guard). We talk about...you guessed it...AI and ethics and throw crypto into the mix for a little extra fun.`,
    thumb: `assets/E98_ Jonathan Benton.jpg`,
    audio: `https://anchor.fm/s/dbb6ced0/podcast/play/65862119/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-2-2%2F315700627-44100-2-098cebe7866045fa.mp3`,
    spotify: `https://podcasters.spotify.com/pod/show/byndthecode/episodes/Lessons-in-AI-and-Ethics-from-a-Crypto-OG---Jonathan-Caras-of-Levana-Protocol-e1vof17`,
    apple: `#`,
    youtube: `#`,
  },
];